spring.application.name=eventhub-producer
azure.eventhub.connection-string=Endpoint=sb://eh-alert-poc-ns.servicebus.windows.net/;SharedAccessKeyName=kafka-access;SharedAccessKey=vdh/z+9d0olTRq86JQH9hp9eyTOBrdpFo+AEhGXsoCI=
azure.eventhub.name=notifications-events

# ========================
# H2 DATABASE
# ========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always