CREATE TABLE payload_mst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload_type VARCHAR(100) NOT NULL,
    payload CLOB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    topic_status VARCHAR(50),
    created_by VARCHAR(100),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP,
    updated_by VARCHAR(100)
);