server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dxp
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true