spring.application.name=eventhub-consumer
server.port=8081
# Event Hub
azure.eventhub.connection-string=Endpoint=sb://eh-alert-poc-ns.servicebus.windows.net/;SharedAccessKeyName=kafka-access;SharedAccessKey=vdh/z+9d0olTRq86JQH9hp9eyTOBrdpFo+AEhGXsoCI=
azure.eventhub.name=notifications-events
azure.eventhub.consumer-group=$Default

# Blob checkpoint
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=alertpocstoragev2;AccountKey=V2L6Pv8KwkIt/rIcQ249vryFTCFRCGBg7dRJ0iXxM32VcJxjdzEu8xKWmXYAAyea7w2OawQxT0DP+ASt4fSl0w==;EndpointSuffix=core.windows.net
azure.storage.container-name=checkpoint-container


# ===============================
# DATABASE CONFIG (MySQL - dxp)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/dxp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# DRIVER
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION POOL (Hikari - default)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000


ldg.api.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlUxc1g4WUZIUzdaNlZsN1ZITEl6VGVqYnZqMCIsImtpZCI6IlUxc1g4WUZIUzdaNlZsN1ZITEl6VGVqYnZqMCJ9.eyJhdWQiOiJhcGk6Ly83NzgzMmFkNC0xZGU5LTRhNGUtYWVkYi0xMGU4ZTM0YWVmYTciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMTRiZTk3NS05YTNmLTQxNjEtODdkOS1lNjIwZTRhMTU0ZmEvIiwiaWF0IjoxNzc2MjE2OTA0LCJuYmYiOjE3NzYyMTY5MDQsImV4cCI6MTc3NjIyMDgwNCwiYWlvIjoiQVNRQTIvOGJBQUFBcklWTG5qZDdZZHZBZTBKZzZPK200cVVwR1ZvZHh6ajJwWUpLR2FtaDh6dz0iLCJhcHBpZCI6Ijc3ODMyYWQ0LTFkZTktNGE0ZS1hZWRiLTEwZThlMzRhZWZhNyIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzAxNGJlOTc1LTlhM2YtNDE2MS04N2Q5LWU2MjBlNGExNTRmYS8iLCJvaWQiOiJhOWQ1YTdlZi1jNWU0LTQ4NWMtOWUzMS1jMzUwZGFjZWEzMDciLCJyaCI6IjEuQVFvQWRlbExBVC1hWVVHSDJlWWc1S0ZVLXRRcWczZnBIVTVLcnRzUTZPTks3NmNBQUFBS0FBLiIsInN1YiI6ImE5ZDVhN2VmLWM1ZTQtNDg1Yy05ZTMxLWMzNTBkYWNlYTMwNyIsInRpZCI6IjAxNGJlOTc1LTlhM2YtNDE2MS04N2Q5LWU2MjBlNGExNTRmYSIsInV0aSI6IlR4S0h3WVJmaWtXRW5GMWdzQmw3QUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfZnRkIjoiOXJZN1NUNmN1bjVzai1ReTBBd0hJYlhxVmpxdFVuYzRfSWlNS2xMcHN4RUJhMjl5WldGemIzVjBhQzFrYzIxeiJ9.oPt4CS-PT0w4-Jf5La76-I_ynrIwvVRAKjQuQbT8c5h-NL-rgJmwrsF4f34k3oeya1lSeAEow0HJnzZdn00U862KlpENDUBIidDurtgfQZ41nLaAgtbX9YQ35X_G4Yw1LlfDUkar9gamhlh7NkqejPbjJPPwX_g72OD-wF40XNqMzHV3hBLTRdK4o6ZJlGuZ-8Sed3clCOas9_oV8sq5HqY8m8D_l4_gdnEzKs8CTMOHuD6Thd-1UV-tKpvKNViy0Iyfsei-QdxiNSfqSbFbKo0lIJk9cayJBZtaYUZwFwDOIuKOJGPUgt6_4ymKQbAYz_ApbeY8G_XWXyKL2UT8xw