spring.application.name=eventhub-consumer
server.port=8081
# Event Hub
azure.eventhub.connection-string=Endpoint=sb://alertpocns01.servicebus.windows.net/;SharedAccessKeyName=kafka-access;SharedAccessKey=jFkymxBll0jPsxFFRcGYpJhjeJZWE4fdy+AEhJeRono=
azure.eventhub.name=notifications.events
azure.eventhub.consumer-group=$Default

# Blob checkpoint
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=alertpocstorage01;AccountKey=c5pTDrSCs1WgrdxFdnrkjXQvoq2rKQkVRA+eKCftz5DPpeBbynB0ETSf3mIi5A3IQOVFYPtM460X+AStE/HlCg==;EndpointSuffix=core.windows.net
azure.storage.container-name=checkpoint-container