show databases;
use dxp;

CREATE TABLE EWB_API_URL_MTB (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    API_ID VARCHAR(100) NOT NULL UNIQUE,
    URL TEXT NOT NULL,
    TYPE VARCHAR(50),
    CONNECTION_TIMEOUT INT,
    READ_TIMEOUT INT,
    AUDIT_FLAG BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    FLEXI_FIELD_1 VARCHAR(255),
    FLEXI_FIELD_2 VARCHAR(255),
    FLEXI_FIELD_3 VARCHAR(255),
    CREATED_BY VARCHAR(100),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);


SET SQL_SAFE_UPDATES = 0;
INSERT INTO EWB_API_URL_MTB 
(API_ID, URL, TYPE, CONNECTION_TIMEOUT, READ_TIMEOUT, AUDIT_FLAG, IS_ACTIVE, CREATED_BY)
VALUES 
('10000', 'http://172.16.112.8:3203/api/ldg/events-logs', 'POST', 5000, 10000, TRUE, TRUE, 'SYSTEM');

CREATE TABLE EWB_API_REQ_RESP_MTB (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    API_ID VARCHAR(100),
    REQUEST LONGTEXT,
    RESPONSE LONGTEXT,
    CREATED_BY VARCHAR(100),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FLEXI_FIELD_1 VARCHAR(255),
    FLEXI_FIELD_2 VARCHAR(255),
    FLEXI_FIELD_3 VARCHAR(255)
);

CREATE TABLE EWB_PAYLOAD_AUDIT_MTB (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PAYLOAD LONGTEXT,
    PARTITION_ID INT,
    OFFSET_VALUE BIGINT,
    SEQUENCE VARCHAR(100),
    STATUS VARCHAR(50),
    CREATED_BY VARCHAR(100),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EWB_CONFIG_MTB (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    `KEY` VARCHAR(100) NOT NULL UNIQUE,
    `VALUE` LONGTEXT NOT NULL,
    MODULE VARCHAR(100) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_ON TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);


INSERT INTO EWB_CONFIG_MTB 
(`KEY`, `VALUE`, MODULE, IS_ACTIVE, CREATED_BY)
VALUES
('LDG_ALLOWED_EVENT_TYPE', 'ewbLoanDocumentProject-creditMemoTLI_AA_ACTIVITY_CLASS_EVENT|ewbLoanDocumentProject-promissoryNoteTLI_AA_ACTIVITY_CLASS_EVENT', 'Lending', TRUE, 'SYSTEM');


INSERT INTO EWB_CONFIG_MTB 
(`KEY`, `VALUE`, MODULE, IS_ACTIVE, CREATED_BY)
VALUES
('LDG_ALLOWED_MESSAGE_TYPE', 'LDG', 'Lending', TRUE, 'SYSTEM');

INSERT INTO EWB_CONFIG_MTB 
(`KEY`, `VALUE`, MODULE, IS_ACTIVE, CREATED_BY)
VALUES
('LDG_ALERT_TYPE', 'promissoryNote-TeachersLoanI-New|creditMemo-TeachersLoanI-New', 'Lending', TRUE, 'SYSTEM');


INSERT INTO EWB_CONFIG_MTB 
(`KEY`, `VALUE`, MODULE, IS_ACTIVE, CREATED_BY)
VALUES
('LDG_ALLOWED_APPLICATION', 'EWRB.LN.TEACHER.SALARY.LOAN.1,LENDING-NEW-ARRANGEMENT|EWRB.LN.TEACHER.SALARY.LOAN.1,LENDING-NEW-ARRANGEMENT', 'Lending', TRUE, 'SYSTEM');

SELECT * FROM EWB_CONFIG_MTB;
commit;